### ISSUE TITLE
I am excited to collaborate

### ISSUE THREAD

**Issue by andyeff** [gmcintire/rick#1]
I have big plans. Big. Plans.

**Comment by ve7cxz** [comment]
WHAT ARE YOUR PLANS ANDY EFF

**Comment by andyeff** [comment]
OMG just you wait! For like, 12 hours!

**Comment by sudomistress** [comment]
I love that this is a fantastically open issue that is almost 2 years old. ;) <3 you guys.

**Comment by gmcintire** [comment]
I'm still waiting

**Comment by andyeff** [comment]
So am I. FOR A BETTER BOT

**Comment by andyeff** [comment]
Wait when did this come on to Github? This isn't the live repo is it, is that still over on t'other VCS ?

**Comment by gmcintire** [comment]
I'm still waiting
